add_newline = false

[git_branch]
symbol = "\uf418 "

[git_state]
merge = "\uf419 "
cherry_pick = "ğŸ’ PICKING"
revert = "âª"
rebase = "ğŸ”€"

[git_status]
conflicted = "\uf440 "
ahead = "ğŸš€ "
behind = "ğŸ¢ "
diverged = "\uf493 "
untracked = "\uf474 "
stashed = "\uf472 "
modified = "\ueade "
staged = "\uf457 "
renamed = "\uf45a "
deleted = "\uf458 "
